version: '3.8'
services:
  postgres:
    image: postgres:13.3
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgres/data
volumes:
  db_data:
